### ISSUE TITLE
[BUG] Metrics Explorer: Changing from Code to Builder doesn't maintain the same query if it was pasted

### ISSUE THREAD

**Issue by bernatixer** [siglens/siglens#1240]
# Description
Switching between the query builder and raw doesn't maintain the query.

# Steps to Reproduce
1. Go to Metrics Explorer
2. Select code input
3. Paste a metric query
4. Go to query builder

# Expected Behavior
The query shown is different on builder and in the raw editors.

# Environment
- SigLens version: 0.2.22

**Comment by nkunal** [comment]
not all queries that are raw edited in "code" mode can be converted to "builder" mode. 
We kept it this way so that if a user wants to try any form of promql query they can put that in the code mode. PromQL queries can get fairly large and complex and may not be possible to convert them in "builder" mode

**Comment by bernatixer** [comment]
> not all queries that are raw edited in "code" mode can be converted to "builder" mode. We kept it this way so that if a user wants to try any form of promql query they can put that in the code mode. PromQL queries can get fairly large and complex and may not be possible to convert them in "builder" mode

Gotcha! Thanks
