### ISSUE TITLE
central authentication for ui

### ISSUE THREAD

**Issue by thatsk** [siglens/siglens#519]
# Description
Authentication for UI

# Benefits
It will be good with some editor and viewer , admin permission so that people can read, modify and update graphs.

# (Optional) Possible Implementation
https://dexidp.io/docs/connectors/
with the help of this it is easily adoptable for ldap or any auth mechanism

**Comment by nkunal** [comment]
This is an enterprise feature

**Comment by jar-work** [comment]
@nkunal I'm just starting to look at the codes, and [I found this method](https://github.com/siglens/siglens/blob/6884e6a330476401fbcec23e45120636d83dd3af/pkg/utils/httpserverutils.go#L799) that can be used for a basic authentication. There are even unit tests (the only references I found are the tests)

We are starting to use siglens for some of our systems, and we need a simple way to block the access to the UI using username and password. I played a bit with the codes and I implemented a simple middleware that handles the authorization:

```
func BasicAuthMiddleware(next fasthttp.RequestHandler) fasthttp.RequestHandler {
	return func(ctx *fasthttp.RequestCtx) {

		var _, user, password = config.GetBasicAuthConfig()  ---> this comes from the server.yaml file
		usernameHash := xxhash.Sum64String(user)
		passwordHash := xxhash.Sum64String(password)

		if !utils.VerifyBasicAuth(ctx, usernameHash, passwordHash) {
			ctx.Response.Header.Add("WWW-Authenticate", `Basic realm="Required username and password"`)
			ctx.Response.SetStatusCode(fasthttp.StatusUnauthorized)
			return
		}

		next(ctx)

	}
}
```
and a function to wrap the routes with that middleware (for now I only tested on top of the routes that require the `tracing.TraceMiddleware`):

```
	getMiddlewares := func(next fasthttp.RequestHandler, requiresTracing bool) fasthttp.RequestHandler {
		var nextToReturn = next

		if requiresTracing {  --> for now passed as parameter
			nextToReturn = tracing.TraceMiddleware(next)
		}

		var authenticationEnabled, _, _ = config.GetBasicAuthConfig() ----> from server.yaml

		if authenticationEnabled {
			nextToReturn = basicauth.BasicAuthMiddleware(nextToReturn)
		}

		return nextToReturn
	}
```
how to use it:

```
	hs.Router.GET(server_utils.API_PREFIX+"/search/live_tail", getMiddlewares(hs.Recovery(liveTailHandler()), true))
	hs.Router.POST(server_utils.API_PREFIX+"/search/live_tail", getMiddlewares(hs.Recovery(liveTailHandler()), true))
```

settings.yaml: 
```
# Basic auth: authorization via username and password for the Query server
basicAuth:
  enabled: true
  user: "siglens-user"
  password: "siglens-password"
```

the settings for the `basicAuth` use a similar structure as [DatabaseConfig](https://github.com/siglens/siglens/blob/6884e6a330476401fbcec23e45120636d83dd3af/pkg/config/common/common.go#L74).

With this, I receive an authentication request whenever I navigate through some of the endpoints that require auth:

![image](https://github.com/siglens/siglens/assets/129268350/9c7ea868-7ef2-4c13-9b13-6840f4aee055)

if the user accepts, all the intercepted calls work with `HTTP 200`. Otherwise, `HTTP 401`

Let me know if this is something you would like to add, to send a PR. For now it's a very basic way to control the access, but at least solves our need.

Thanks in advance,
