### ISSUE TITLE
[BUG] Issue - X does not show up  at the end of a query when we run query using `free text` , go to `Query Builder` tab and come back to  `free text` tab.

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#588]
# Description
On Search page , under free text search  tab X does not show up  at the end of a query when we run query using `free text` , go to `Query Builder` tab and come back to  `free text` tab.

Steps to reproduce
1. On Search page , under free text search  , enter query
2. click on `Query Builder` tab
3. come back to `free text` tab
4.  X does not show up  at the end of a query

# Expected Behavior
Clearly describe what you expect to happen.

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by Varun710** [comment]
Hello @sunitakawane ,

I'm eager to contribute to SigLens. This is my first time contributing to open source, so could you please provide some guidance on how to get started with this issue? I went through the CONTRIBUTING.md and it's a little intimidating. Any advice would be greatly appreciated.

Thank you!
Varun

**Comment by AndrewHess** [comment]
From the CONTRIBUTING.md, you'll want to look at the [Development Environment Setup](https://github.com/siglens/siglens/blob/develop/CONTRIBUTING.md#development-environment-setup) so that you can run siglens locally from source code. To do this you'll want to fork the siglens repo. Then following the "Start up Siglens" section you should be able to run siglens from source code and access the UI at http://localhost:5122

Next you can send data following the "Send Data to SigLens" section, and after a few seconds you can refresh the UI page and you should see the data there (on the Logs tab, which is the default tab that opens when you go to the UI).

Now that you can run siglens, access the UI, and use sample data, you're ready to start making changes. For this issue I think it will just be a frontend bug, so you'll probably only have to fix some JS code within the `static/js/` directory.

You'll also want to look at the "Pull Request Lifecycle" section and follow those steps when making your PR.

Let me know if you have more questions. And thanks for the feedback, we should make the steps a little more clear and easy to follow.

**Comment by Varun710** [comment]
Hey. Thanks for the quick reply. It's really helpful. I will go through this and let you know if I face any issues.

**Comment by Amith-CS** [comment]
I want to work on this issue!

**Comment by nbhavana** [comment]
go ahead
